# Generated by Django 5.1 on 2024-08-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstock',
            name='stock_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
